spring:
  application:
    name: customer-service

server:
  port: 11110

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:11140/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
