#spring:
#  application:
#    name: payment-service

server:
  port: 11114

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:11140/eureka/
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    hostname: payment-service