#Configuration discovery server
spring:
  application:
    name: discovery

server:
    port: 11140

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false